spring:
  config:
    activate:
      on-profile: develop

  datasource:
    url: jdbc:h2:mem:connect_post
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: 192.168.1.12
      port: 6379

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false